/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import com.mysql.jdbc.Connection;
import java.awt.GridBagLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;
import mybanksystem.MainScreen;
import mybanksystem.MySqlConnect;

/**
 *
 * @author yangp
 */
public class DepositConfirm extends javax.swing.JPanel {
    
    String[] getdata = new String[4];
    DepositC depositBack;
    DepositC depositFrom;
    String password;
    double money;
 
    

    /**
     * Creates new form DepositConfirm
     */
//    public DepositConfirm() {
//        initComponents();   
//    }
    
    public DepositConfirm() {
        initComponents();   
    }
    
    public DepositConfirm(DepositC d) {
        initComponents();   
        depositFrom = d;
        String cardno = depositFrom.getcardno().getText();
        String cardname = depositFrom.getcardname().getText();
        try{
            Connection con = MySqlConnect.ConnectDB(); 
            String query = "select * from acctinfo where cardNo = ? and acctName = ?" ;
                          
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, cardno);
            st.setString(2, cardname);
            ResultSet result  = st.executeQuery();
          
            if(result.next() ){
                accountNumTF.setText(result.getString("acctNo"));
                acctNameTF.setText(result.getString("acctName"));
                balanceTF.setText(result.getString("balance"));                
                cardNumTF.setText(result.getString("cardNo"));
                amtTF.setText(depositFrom.getamt().getText());
                currencyTF.setSelectedItem(depositFrom.getcurrency().getSelectedItem());
                password = result.getString("cardPassword");
            }
            else{
                 JOptionPane.showMessageDialog(null, "There is no eligible record, please check!!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Research failed! \n " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositconfirmPanel = new javax.swing.JPanel();
        confirmPanelBotm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        backButn = new javax.swing.JButton();
        enterButn = new javax.swing.JButton();
        confirmPanel = new javax.swing.JPanel();
        acctNameTF = new javax.swing.JTextField();
        accountNumTF = new javax.swing.JTextField();
        amtTF = new javax.swing.JTextField();
        currencyTF = new javax.swing.JComboBox<>();
        amtL = new javax.swing.JLabel();
        currencyL = new javax.swing.JLabel();
        accountNumL = new javax.swing.JLabel();
        accountNameL = new javax.swing.JLabel();
        cardNumL = new javax.swing.JLabel();
        cardNumTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        depositconfirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        depositconfirmPanel.setLayout(null);

        confirmPanelBotm.setBackground(new java.awt.Color(255, 255, 255));
        confirmPanelBotm.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Cash Deposit");
        confirmPanelBotm.add(jLabel1);
        jLabel1.setBounds(180, 30, 140, 60);

        passwordL.setFont(passwordL.getFont().deriveFont(passwordL.getFont().getSize()+1f));
        passwordL.setText("Transaction Password:");
        confirmPanelBotm.add(passwordL);
        passwordL.setBounds(50, 420, 190, 21);

        passwordTF.setFont(passwordTF.getFont().deriveFont(passwordTF.getFont().getSize()+1f));
        confirmPanelBotm.add(passwordTF);
        passwordTF.setBounds(260, 420, 210, 27);

        backButn.setText("Back");
        backButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButnActionPerformed(evt);
            }
        });
        confirmPanelBotm.add(backButn);
        backButn.setBounds(255, 470, 90, 29);

        enterButn.setText("Enter");
        enterButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButnActionPerformed(evt);
            }
        });
        confirmPanelBotm.add(enterButn);
        enterButn.setBounds(380, 470, 100, 29);

        confirmPanel.setBackground(new java.awt.Color(255, 255, 255));
        confirmPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        acctNameTF.setFont(acctNameTF.getFont().deriveFont(acctNameTF.getFont().getSize()+1f));
        acctNameTF.setEnabled(false);

        accountNumTF.setFont(accountNumTF.getFont().deriveFont(accountNumTF.getFont().getSize()+1f));
        accountNumTF.setEnabled(false);
        accountNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumTFActionPerformed(evt);
            }
        });

        amtTF.setFont(amtTF.getFont().deriveFont(amtTF.getFont().getSize()+1f));
        amtTF.setEnabled(false);

        currencyTF.setFont(currencyTF.getFont().deriveFont(currencyTF.getFont().getSize()+1f));
        currencyTF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RMB", "USD" }));
        currencyTF.setEnabled(false);

        amtL.setFont(amtL.getFont().deriveFont(amtL.getFont().getSize()+1f));
        amtL.setText("Transaction Amount:");

        currencyL.setFont(currencyL.getFont().deriveFont(currencyL.getFont().getSize()+1f));
        currencyL.setText("Currency:");

        accountNumL.setFont(accountNumL.getFont().deriveFont(accountNumL.getFont().getSize()+1f));
        accountNumL.setText("Account Num:");

        accountNameL.setFont(accountNameL.getFont().deriveFont(accountNameL.getFont().getSize()+1f));
        accountNameL.setText("Account Name:");

        cardNumL.setFont(cardNumL.getFont().deriveFont(cardNumL.getFont().getSize()+1f));
        cardNumL.setText("Card Num:");

        cardNumTF.setFont(cardNumTF.getFont().deriveFont(cardNumTF.getFont().getSize()+1f));
        cardNumTF.setEnabled(false);
        cardNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance: ");

        balanceTF.setEnabled(false);

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmPanelLayout.createSequentialGroup()
                        .addComponent(accountNumL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(accountNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmPanelLayout.createSequentialGroup()
                        .addComponent(accountNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmPanelLayout.createSequentialGroup()
                        .addComponent(cardNumL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPanelLayout.createSequentialGroup()
                        .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amtL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currencyL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currencyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amtTF, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(balanceTF))))
                .addContainerGap())
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumL)
                    .addComponent(accountNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNameL)
                    .addComponent(acctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amtL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyL)
                    .addComponent(currencyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        confirmPanelBotm.add(confirmPanel);
        confirmPanel.setBounds(20, 120, 470, 290);

        depositconfirmPanel.add(confirmPanelBotm);
        confirmPanelBotm.setBounds(-10, -10, 540, 550);

        add(depositconfirmPanel);
        depositconfirmPanel.setBounds(0, 0, 530, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void accountNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumTFActionPerformed

    private void backButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButnActionPerformed

     
        depositBack = new DepositC(cardNumTF.getText(),acctNameTF.getText(),amtTF.getText(),String.valueOf(currencyTF.getSelectedItem())); 
        depositBack.setData();
        depositconfirmPanel.setLayout(new java.awt.BorderLayout());
        depositconfirmPanel.add(depositBack);
        depositconfirmPanel.setVisible(true);
        confirmPanel.setVisible(false);
        confirmPanelBotm.setVisible(false);
        depositconfirmPanel.revalidate();
        depositconfirmPanel.repaint(); 
       
       
    }//GEN-LAST:event_backButnActionPerformed

    private void enterButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButnActionPerformed
          String k = String.valueOf(passwordTF.getPassword());
        if(password.equals(k)){
         try{
            if((balanceTF.getText()).equals("")) {
             money = Double.parseDouble(amtTF.getText());
           }
            else{         
            money = Double.parseDouble(amtTF.getText())  + Double.parseDouble(balanceTF.getText());
           }
            
            String moneyresult = String.valueOf(money);
            Connection con = MySqlConnect.ConnectDB(); 
            String query = "update acctinfo set balance = ?,currency = ? where cardNo = ? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1,moneyresult);
            st.setString(2,currencyTF.getSelectedItem().toString());
            st.setString(3,cardNumTF.getText());
            int result  = st.executeUpdate();
          
            if(result > 0 ){
                JOptionPane.showMessageDialog(null, "Transaction is successful !!");
                this.setVisible(false);
                
            }
            else{
                 JOptionPane.showMessageDialog(null, "Transaction Failed !!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Research failed! \n " + e);
        }
     }else{
         JOptionPane.showMessageDialog(null, "Password is NOT correct!!");
     }
    }//GEN-LAST:event_enterButnActionPerformed

    private void cardNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumTFActionPerformed


    ///set data from perious screen before show up the confirm screen 
    public void setData(String[] passdata){
        
        accountNumTF.setText(passdata[0]);
        acctNameTF.setText(passdata[1]);
        amtTF.setText(passdata[2]);
        currencyTF.setSelectedItem(passdata[3]);
        getdata = Arrays.copyOf(passdata, passdata.length);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNameL;
    private javax.swing.JLabel accountNumL;
    private javax.swing.JTextField accountNumTF;
    private javax.swing.JTextField acctNameTF;
    private javax.swing.JLabel amtL;
    private javax.swing.JTextField amtTF;
    private javax.swing.JButton backButn;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JLabel cardNumL;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JPanel confirmPanelBotm;
    private javax.swing.JLabel currencyL;
    private javax.swing.JComboBox<String> currencyTF;
    private javax.swing.JPanel depositconfirmPanel;
    private javax.swing.JButton enterButn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
