/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mybanksystem.MySqlConnect;



/**
 *
 * @author yangp
 */
public class DepositC extends javax.swing.JPanel {
  
    
    DepositConfirm confirmscreen ;
    String num, name,amt,currency;
    String[] datapass = new String[4];
    /**
     * Creates new form DepositC
     */
    public DepositC(String num, String name, String amt, String currency) {
        initComponents();
        this.num = num;
        this.name = name;
        this.amt = amt;
        this.currency = currency;
        
    }
     public DepositC(){
        initComponents();
        confirmscreen = new DepositConfirm();
        depositconfirmshow.setLayout(new java.awt.BorderLayout());
        depositconfirmshow.add(confirmscreen);
        confirmscreen.setVisible(false); 
     }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositconfirmshow = new javax.swing.JPanel();
        depositPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardNumTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cardNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        currencyCB = new javax.swing.JComboBox<>();
        nextButn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        depositconfirmshow.setBackground(new java.awt.Color(255, 255, 255));
        depositconfirmshow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        depositconfirmshow.setForeground(new java.awt.Color(255, 255, 255));
        depositconfirmshow.setEnabled(false);
        depositconfirmshow.setLayout(null);

        depositPanel.setBackground(new java.awt.Color(255, 255, 255));
        depositPanel.setLayout(null);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+1f));
        jLabel2.setText("Card Num:");
        depositPanel.add(jLabel2);
        jLabel2.setBounds(70, 170, 180, 21);

        cardNumTF.setFont(cardNumTF.getFont().deriveFont(cardNumTF.getFont().getSize()+1f));
        depositPanel.add(cardNumTF);
        cardNumTF.setBounds(260, 170, 200, 27);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+1f));
        jLabel3.setText("Card Name:");
        depositPanel.add(jLabel3);
        jLabel3.setBounds(70, 210, 180, 21);

        cardNameTF.setFont(cardNameTF.getFont().deriveFont(cardNameTF.getFont().getSize()+1f));
        depositPanel.add(cardNameTF);
        cardNameTF.setBounds(260, 210, 200, 27);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+1f));
        jLabel4.setText("Transaction Amount:");
        depositPanel.add(jLabel4);
        jLabel4.setBounds(70, 250, 180, 21);

        amountTF.setFont(amountTF.getFont().deriveFont(amountTF.getFont().getSize()+1f));
        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });
        depositPanel.add(amountTF);
        amountTF.setBounds(260, 250, 200, 27);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+1f));
        jLabel5.setText("Currency:");
        depositPanel.add(jLabel5);
        jLabel5.setBounds(70, 290, 150, 21);

        currencyCB.setFont(currencyCB.getFont().deriveFont(currencyCB.getFont().getSize()+1f));
        currencyCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "RMB" }));
        depositPanel.add(currencyCB);
        currencyCB.setBounds(260, 290, 66, 27);

        nextButn.setText("Next");
        nextButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButnActionPerformed(evt);
            }
        });
        depositPanel.add(nextButn);
        nextButn.setBounds(210, 390, 65, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Cash Deposit");
        depositPanel.add(jLabel1);
        jLabel1.setBounds(190, 50, 160, 60);

        depositconfirmshow.add(depositPanel);
        depositPanel.setBounds(10, 0, 560, 550);

        add(depositconfirmshow);
        depositconfirmshow.setBounds(0, 0, 570, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButnActionPerformed
            if((cardNumTF.getText()).equals("")){
                JOptionPane.showMessageDialog(null, "Crad Number must be entered !!");
            }else if((cardNameTF.getText()).equals("")){
                JOptionPane.showMessageDialog(null, "Card Name must be entered !!");
            }else if((amountTF.getText()).equals("")){
                JOptionPane.showMessageDialog(null, "Amount must be entered !!");
            }else{
           
             
                depositPanel.setVisible(false);   
                confirmscreen = new DepositConfirm(this);
                depositconfirmshow.setLayout(new java.awt.BorderLayout());
                depositconfirmshow.add(confirmscreen);
                confirmscreen.setVisible(false); 

                 try{
           
                        Connection con = MySqlConnect.ConnectDB(); 
                        String query = "select * from acctinfo where cardNo = ? and acctName = ?";
                        PreparedStatement st = con.prepareStatement(query);
                        st.setString(1, cardNumTF.getText());
                        st.setString(2, cardNameTF.getText());
                   
                        ResultSet result = st.executeQuery();
                        if(result.next()){
                            confirmscreen.setVisible(true); 
                        }else{
                            JOptionPane.showMessageDialog(null,"Card number or card name is WRONG! \nPlease check and try again!");
                        }
                        }catch(Exception ex){
                    
                        JOptionPane.showMessageDialog(null,"Search data failed! \n" + ex);
                     }  
        
            }
    
    }//GEN-LAST:event_nextButnActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed


    public void setData(){
        cardNumTF.setText(this.num);
        cardNameTF.setText(name);
        amountTF.setText(amt);
        currencyCB.setSelectedItem(currency);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField cardNameTF;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JComboBox<String> currencyCB;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JPanel depositconfirmshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nextButn;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField getcardno(){
        return this.cardNumTF;
    }
    
    public javax.swing.JTextField getcardname(){
        return this.cardNameTF;
    }
    public javax.swing.JTextField getamt(){
        return this.amountTF;
    }
    public javax.swing.JComboBox<String> getcurrency(){
        return this.currencyCB;
    }
    
}
