/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mybanksystem.DealInTransaction;
import mybanksystem.MySqlConnect;

/**
 *
 * @author yangp
 */
public class InTransactionPend extends javax.swing.JPanel {
   
    int j = 1;
    boolean[] statuscheck = new boolean[4];
    String [] input = new String[4];
    /**
     * Creates new form InTransactionPend
     */
    public InTransactionPend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InTransactionPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        rm = new javax.swing.JLabel();
        accountNum = new javax.swing.JLabel();
        flowNumTF = new javax.swing.JTextField();
        accountNumTF = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        searchButn = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        nextButn = new javax.swing.JButton();
        cancelButn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        InTransactionPanel.setBackground(new java.awt.Color(255, 255, 255));
        InTransactionPanel.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("In-Transaction Pending");
        InTransactionPanel.add(title);
        title.setBounds(130, 30, 290, 29);

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        rm.setText("Flow Num:");

        accountNum.setText("Account Num:");

        date.setText("Date:");

        amount.setText("Amount:");

        searchButn.setText("Search");
        searchButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNum)
                    .addComponent(date)
                    .addComponent(amount))
                .addGap(36, 36, 36)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(searchButn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rm)
                    .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNum)
                    .addComponent(accountNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButn)
                        .addGap(8, 8, 8))))
        );

        InTransactionPanel.add(searchPanel);
        searchPanel.setBounds(20, 70, 500, 180);

        resultPanel.setBackground(new java.awt.Color(255, 255, 255));
        resultPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flow Num", "Inward Account Num", "Inward Name", "Inward Date", "Inward Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        InTransactionPanel.add(resultPanel);
        resultPanel.setBounds(20, 260, 500, 240);

        nextButn.setText("Deal ");
        nextButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButnActionPerformed(evt);
            }
        });
        InTransactionPanel.add(nextButn);
        nextButn.setBounds(400, 530, 93, 29);

        cancelButn.setText("Cancel");
        cancelButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButnActionPerformed(evt);
            }
        });
        InTransactionPanel.add(cancelButn);
        cancelButn.setBounds(290, 530, 80, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InTransactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InTransactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButnActionPerformed
        DealInTransaction dealtransaction = new DealInTransaction(this);
        dealtransaction.setVisible(true);
    }//GEN-LAST:event_nextButnActionPerformed

    private void searchButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButnActionPerformed
         String query =  " select * from intransaction where transactionStatus = \"DCHULI\" ";
        input[0] = flowNumTF.getText();
        input[1] = accountNumTF.getText();
        input[2] = dateTF.getText();
        input[3] = amountTF.getText();
        if(!(input[0]).equals("")){
            query = query + " and flowNum = ?";
            statuscheck[0] = true;
        }
        if(!(input[1]).equals("")){
            query = query + " and payeeAcctNum = ?";
            statuscheck[1] = true;
        }
        if(!(input[2]).equals("")){
            query = query + " and receivedDate = ?";
            statuscheck[2] = true;
        }
         if(!(input[3]).equals("")){
            query = query + " and transactionAmt = ?";
            statuscheck[3] = true;
        }
         try{
             Connection con = MySqlConnect.ConnectDB();
             PreparedStatement st = con.prepareStatement(query);
              j = 1;
             for(int i =0;i<4;i++){
                if(statuscheck[i]== true){
                 st.setString(j, input[i]);
                 j++;
                 statuscheck[i]= false;
                    }
            }
             
             ResultSet result = st.executeQuery();
             for(int k=0;k<13;k++){
                 table.getModel().setValueAt(null, k, 0);
                 table.getModel().setValueAt(null, k, 1);
                 table.getModel().setValueAt(null, k, 2);
                 table.getModel().setValueAt(null, k, 3);
                 table.getModel().setValueAt(null, k, 4);
             }
             int i=0;
             if(result.next()){
                   
                 do{
                    Object flowNums = result.getString("flowNum");
                    Object acctNums = result.getString("payeeAcctNum");
                    Object acctNames = result.getString("payeeAcctName");
                    Object dates = result.getString("receivedDate");
                    Object amts = result.getString("transactionAmt");
                 
                 
                    table.getModel().setValueAt(flowNums, i, 0);
                    table.getModel().setValueAt(acctNums, i, 1);
                    table.getModel().setValueAt(acctNames, i, 2);
                    table.getModel().setValueAt(dates, i, 3);
                    table.getModel().setValueAt(amts, i, 4);
                    i++;
                }while(result.next());
             }else{         
                JOptionPane.showMessageDialog(null, "There is no qualified record ! ");
            }
             
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Search failed ! " + e);
         }
         
        
      
                
        
    }//GEN-LAST:event_searchButnActionPerformed

    private void cancelButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InTransactionPanel;
    private javax.swing.JLabel accountNum;
    private javax.swing.JTextField accountNumTF;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton cancelButn;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField flowNumTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButn;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel rm;
    private javax.swing.JButton searchButn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getmainpanel(){
        return this.InTransactionPanel;
    }
    public javax.swing.JTable gettable(){
        return this.table;
    }
}
