/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import com.mysql.jdbc.Connection;
import java.awt.Component;
import java.awt.Container;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mybanksystem.MySqlConnect;
import mybanksystem.OBTransferConfirm;
import mybanksystem.SBtransferConfirm;

/**
 *
 * @author yangp
 */
public class TransferOtherB extends javax.swing.JPanel {
    public String acctno = null;
    public String password = null;
    public String idno = null;
    public String idtype = null;
    /**
     * Creates new form TransferOtherB1
     */
    public TransferOtherB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otherBankTransferPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        payerPanel = new javax.swing.JPanel();
        accountNum = new javax.swing.JLabel();
        acountName = new javax.swing.JLabel();
        AMT = new javax.swing.JLabel();
        cardNumTF = new javax.swing.JTextField();
        cardNameTF = new javax.swing.JTextField();
        balanceTF = new javax.swing.JTextField();
        balanceCurrency = new javax.swing.JTextField();
        idType = new javax.swing.JLabel();
        idNum = new javax.swing.JLabel();
        bankNoTF = new javax.swing.JTextField();
        bankNameTF = new javax.swing.JTextField();
        searchButn = new javax.swing.JButton();
        payeePanel = new javax.swing.JPanel();
        payeeAcct = new javax.swing.JLabel();
        payeeName = new javax.swing.JLabel();
        payeeAMT = new javax.swing.JLabel();
        payeeAcctTF = new javax.swing.JTextField();
        payeeNameTF = new javax.swing.JTextField();
        payeeAmtTF = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        currencyCB = new javax.swing.JComboBox<>();
        payeeBankNo = new javax.swing.JLabel();
        payeeBankNoTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        payeeBankNameTF = new javax.swing.JTextField();
        cardNum = new javax.swing.JLabel();
        payeeCardNumTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nextButn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        otherBankTransferPanel.setBackground(new java.awt.Color(255, 255, 255));
        otherBankTransferPanel.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Transfer (Other Bank)");
        otherBankTransferPanel.add(title);
        title.setBounds(160, 20, 270, 29);

        payerPanel.setBackground(new java.awt.Color(255, 255, 255));
        payerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Payer Information"));
        payerPanel.setEnabled(false);
        payerPanel.setLayout(null);

        accountNum.setText("Card Num:");
        payerPanel.add(accountNum);
        accountNum.setBounds(57, 25, 125, 20);

        acountName.setText("Card Name:");
        payerPanel.add(acountName);
        acountName.setBounds(57, 60, 125, 20);

        AMT.setText("Account Balance:");
        payerPanel.add(AMT);
        AMT.setBounds(57, 95, 125, 20);
        payerPanel.add(cardNumTF);
        cardNumTF.setBounds(200, 20, 219, 26);
        payerPanel.add(cardNameTF);
        cardNameTF.setBounds(200, 60, 219, 26);

        balanceTF.setEnabled(false);
        payerPanel.add(balanceTF);
        balanceTF.setBounds(200, 90, 115, 26);

        balanceCurrency.setEnabled(false);
        payerPanel.add(balanceCurrency);
        balanceCurrency.setBounds(320, 90, 100, 26);

        idType.setText("Bank No:");
        payerPanel.add(idType);
        idType.setBounds(57, 130, 120, 20);

        idNum.setText("Bank Name:");
        payerPanel.add(idNum);
        idNum.setBounds(57, 167, 120, 20);
        payerPanel.add(bankNoTF);
        bankNoTF.setBounds(200, 130, 219, 26);
        payerPanel.add(bankNameTF);
        bankNameTF.setBounds(200, 170, 219, 26);

        searchButn.setText("search");
        searchButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButnActionPerformed(evt);
            }
        });
        payerPanel.add(searchButn);
        searchButn.setBounds(420, 60, 80, 29);

        otherBankTransferPanel.add(payerPanel);
        payerPanel.setBounds(20, 70, 510, 200);

        payeePanel.setBackground(new java.awt.Color(255, 255, 255));
        payeePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Payee Information"));
        payeePanel.setEnabled(false);
        payeePanel.setLayout(null);

        payeeAcct.setText("Payee Account:");
        payeePanel.add(payeeAcct);
        payeeAcct.setBounds(50, 60, 132, 20);

        payeeName.setText("Payee Name:");
        payeePanel.add(payeeName);
        payeeName.setBounds(50, 100, 132, 20);

        payeeAMT.setText("Payee Amount:");
        payeePanel.add(payeeAMT);
        payeeAMT.setBounds(50, 130, 132, 20);
        payeePanel.add(payeeAcctTF);
        payeeAcctTF.setBounds(200, 60, 221, 26);
        payeePanel.add(payeeNameTF);
        payeeNameTF.setBounds(200, 100, 221, 26);
        payeePanel.add(payeeAmtTF);
        payeeAmtTF.setBounds(200, 130, 221, 26);

        currency.setText("Currency:");
        payeePanel.add(currency);
        currency.setBounds(50, 170, 132, 20);

        currencyCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "RMB" }));
        payeePanel.add(currencyCB);
        currencyCB.setBounds(200, 170, 92, 26);

        payeeBankNo.setText("Payee Bank No:");
        payeePanel.add(payeeBankNo);
        payeeBankNo.setBounds(50, 200, 132, 20);
        payeePanel.add(payeeBankNoTF);
        payeeBankNoTF.setBounds(200, 200, 221, 26);

        jLabel1.setText("Payee Bank Name:");
        payeePanel.add(jLabel1);
        jLabel1.setBounds(50, 240, 132, 20);
        payeePanel.add(payeeBankNameTF);
        payeeBankNameTF.setBounds(200, 240, 221, 26);

        cardNum.setText("Card Num:");
        payeePanel.add(cardNum);
        cardNum.setBounds(50, 30, 100, 20);
        payeePanel.add(payeeCardNumTF);
        payeeCardNumTF.setBounds(200, 20, 220, 26);

        otherBankTransferPanel.add(payeePanel);
        payeePanel.setBounds(20, 270, 510, 270);

        jButton1.setText("Cancel");
        otherBankTransferPanel.add(jButton1);
        jButton1.setBounds(290, 540, 110, 29);

        nextButn.setText("Next");
        nextButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButnActionPerformed(evt);
            }
        });
        otherBankTransferPanel.add(nextButn);
        nextButn.setBounds(440, 540, 90, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otherBankTransferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otherBankTransferPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButnActionPerformed
        
        if((payeeAcctTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Payee account number must be entered !!");
        }else if ((payeeCardNumTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Payee card no must be entered !!");
        }else if((payeeNameTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Payee account name must be entered !!");
        }else if((payeeAmtTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Transaction amount must be entered !!");
        }else if((payeeBankNoTF.getText()).equals("")){
             JOptionPane.showMessageDialog(null, "Bank NO must be entered !!");
        }else if((payeeBankNameTF.getText()).equals("")){
             JOptionPane.showMessageDialog(null, "Bank Name must be entered !!");
        }else{
            
            
            
            
            
             OBTransferConfirm confirm = new OBTransferConfirm(this);
             confirm.setVisible(true);
             setEnableRec(otherBankTransferPanel,false);
        }
        
    }//GEN-LAST:event_nextButnActionPerformed

    private void searchButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButnActionPerformed
        
        if((cardNumTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Card Number must be entered !!");
        }else if((cardNameTF.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "Card Name must be entered !!");
        }else{
            try{
           
             Connection con = MySqlConnect.ConnectDB(); 
             String query = "select * from acctinfo where cardNo = ? and acctName = ?";
              PreparedStatement st = con.prepareStatement(query);
              st.setString(1, cardNumTF.getText());
              st.setString(2, cardNameTF.getText());
             
              ResultSet result = st.executeQuery();
              
              if(result.next()){
                   acctno = result.getString("acctNo");
                   password = result.getString("cardPassword");
                   balanceTF.setText(result.getString("balance"));
                   balanceCurrency.setText(result.getString("currency"));
                   idtype = (result.getString("applicantIDType"));
                   idno = (result.getString("applicantIDNum"));
              }else{
                  JOptionPane.showMessageDialog(null, "There is no eligible record !!");
              }
             
     
          } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Search data failed! \n" + ex);
        }
       }
                                              
    }//GEN-LAST:event_searchButnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMT;
    private javax.swing.JLabel accountNum;
    private javax.swing.JLabel acountName;
    private javax.swing.JTextField balanceCurrency;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JTextField bankNameTF;
    private javax.swing.JTextField bankNoTF;
    private javax.swing.JTextField cardNameTF;
    private javax.swing.JLabel cardNum;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JLabel currency;
    private javax.swing.JComboBox<String> currencyCB;
    private javax.swing.JLabel idNum;
    private javax.swing.JLabel idType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButn;
    private javax.swing.JPanel otherBankTransferPanel;
    private javax.swing.JLabel payeeAMT;
    private javax.swing.JLabel payeeAcct;
    private javax.swing.JTextField payeeAcctTF;
    private javax.swing.JTextField payeeAmtTF;
    private javax.swing.JTextField payeeBankNameTF;
    private javax.swing.JLabel payeeBankNo;
    private javax.swing.JTextField payeeBankNoTF;
    private javax.swing.JTextField payeeCardNumTF;
    private javax.swing.JLabel payeeName;
    private javax.swing.JTextField payeeNameTF;
    private javax.swing.JPanel payeePanel;
    private javax.swing.JPanel payerPanel;
    private javax.swing.JButton searchButn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
     public javax.swing.JPanel getmainpanel(){
        return this.otherBankTransferPanel;
    }
    
    public javax.swing.JTextField getpayname(){
        return this.cardNameTF;
    }
    public javax.swing.JTextField getcardnum(){
        return this.cardNumTF;
    }
    
    public javax.swing.JTextField getbalance(){
        return this.balanceTF;
    }
   
    
    public javax.swing.JTextField getpayeeacct(){
        return this.payeeAcctTF;
    }
    public javax.swing.JTextField getpayeename(){
        return this.payeeNameTF;
    }
    public javax.swing.JTextField getamt(){
        return this.payeeAmtTF;
    }
    public javax.swing.JComboBox<String> getpayeecurrency(){
        return this.currencyCB;
    }
    
     public javax.swing.JTextField getbankno(){
        return this.bankNoTF;
    }
     
      public javax.swing.JTextField getbankname(){
        return this.bankNameTF;
    }
      
     public javax.swing.JTextField getpayeebankno(){
        return this.bankNoTF;
    }
     
      public javax.swing.JTextField getpayeebankname(){
        return this.payeeBankNoTF;
    }
      
       public javax.swing.JTextField getpayeecardno(){
        return this.payeeBankNameTF;
    }
      
    
    
     ///disable the panel when new frame show up
  public void setEnableRec(Component container, boolean enable){
    container.setEnabled(enable);

    try {
        Component[] components= ((Container) container).getComponents();
        for (int i = 0; i < components.length; i++) {
            setEnableRec(components[i], enable);
        }
    } catch (ClassCastException e) {
        System.out.println("there is error");
    }
}
}
