/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author yangp
 */
public class DealInTransactionConfirm extends javax.swing.JFrame {
        DealInTransaction intrans;
        String CB;
    /**
     * Creates new form DealInTransactionConfirm
     */
    public DealInTransactionConfirm() {
        initComponents();
    }
    
    public DealInTransactionConfirm(DealInTransaction d) {
        initComponents();
        intrans = d;
        payAcctNumTF.setText(intrans.getpayacctno().getText());
        payerAcctNameTF.setText(intrans.getpayacctname().getText());
        flowNumTF.setText(intrans.getflownum().getText());
        dataTF.setText(intrans.getdata().getText());
        payerBankNoTF.setText(intrans.getpaybankno().getText());
        payerBankNameTF.setText(intrans.getpaybankname().getText());
        payeeAcctNumTF.setText(intrans.getpayeeacctno().getText());
        payeeAcctNameTF.setText(intrans.getpayeeacctname().getText());
        payeeBankNoTF.setText(intrans.getpayeebankno().getText());
        payeeBankNameTF.setText(intrans.getpayeebankname().getText());
        amountTF.setText(intrans.getamount().getText());
        currencyTF.setText(intrans.getcurrency().getText());
        reasonTF.setText(intrans.getreason().getText());   
        prestatusTF.setText(intrans.getprestatus().getText());
        statusTF.setText(intrans.getstatus().getText());
        postCardNoTF.setText(intrans.getpostacctno().getText());
        postAcctNameTF.setText(intrans.getpostacctname().getText());
        CB = intrans.getdealtype().getSelectedItem().toString();
        dealTypeCB.setSelectedItem(intrans.getdealtype().getSelectedItem().toString());
        if(CB.equals("Post  to Account")){
            glAcctL.setVisible(false);
            GLAccountCB.setVisible(false);
        }else if(CB.equals("Handing to GL Account")){
            postAcctL.setVisible(false);
            postCardNoTF.setVisible(false);
            acctname.setVisible(false);
            postAcctNameTF.setVisible(false);
        }else{
            glAcctL.setVisible(false);
            GLAccountCB.setVisible(false);
            postAcctL.setVisible(false);
            postCardNoTF.setVisible(false);
            acctname.setVisible(false);
            postAcctNameTF.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealInTransaction = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        otherbank = new javax.swing.JPanel();
        payeracctNum = new javax.swing.JLabel();
        payerAcctName = new javax.swing.JLabel();
        payerBankNo = new javax.swing.JLabel();
        payerBankName = new javax.swing.JLabel();
        payAcctNumTF = new javax.swing.JTextField();
        payerAcctNameTF = new javax.swing.JTextField();
        payerBankNoTF = new javax.swing.JTextField();
        payerBankNameTF = new javax.swing.JTextField();
        flowNum = new javax.swing.JLabel();
        flowNumTF = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dataTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        prestatusTF = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ourbank = new javax.swing.JPanel();
        payeeAcctNum = new javax.swing.JLabel();
        payeeAcctName = new javax.swing.JLabel();
        payeeAcctNumTF = new javax.swing.JTextField();
        payeeBankNo = new javax.swing.JLabel();
        payeeBankName = new javax.swing.JLabel();
        payeeBankNameTF = new javax.swing.JTextField();
        payeeBankNoTF = new javax.swing.JTextField();
        payeeAcctNameTF = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        reason = new javax.swing.JLabel();
        reasonTF = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        currencyTF = new javax.swing.JTextField();
        dealing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dealTypeCB = new javax.swing.JComboBox<>();
        postAcctL = new javax.swing.JLabel();
        postCardNoTF = new javax.swing.JTextField();
        glAcctL = new javax.swing.JLabel();
        GLAccountCB = new javax.swing.JComboBox<>();
        acctname = new javax.swing.JLabel();
        postAcctNameTF = new javax.swing.JTextField();
        backButn = new javax.swing.JButton();
        okButn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dealInTransaction.setBackground(new java.awt.Color(255, 255, 255));
        dealInTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        dealInTransaction.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("In-Transaction Pending Confirm");
        dealInTransaction.add(title);
        title.setBounds(190, 30, 390, 29);

        otherbank.setBackground(new java.awt.Color(255, 255, 255));
        otherbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Other Bank Information"));
        otherbank.setEnabled(false);

        payeracctNum.setText("Payer Account Num:");

        payerAcctName.setText("Payer Account Name:");

        payerBankNo.setText("Payer Bank No:");

        payerBankName.setText("Payer Bank Name:");

        payAcctNumTF.setEnabled(false);

        payerAcctNameTF.setEnabled(false);

        payerBankNoTF.setEnabled(false);

        payerBankNameTF.setEnabled(false);

        flowNum.setText("Flow Num:");

        flowNumTF.setEnabled(false);

        date.setText("Received Date:");

        dataTF.setEnabled(false);

        jLabel1.setText("Pre Status:");

        prestatusTF.setEnabled(false);

        statusTF.setEnabled(false);

        jLabel2.setText("Status:");

        javax.swing.GroupLayout otherbankLayout = new javax.swing.GroupLayout(otherbank);
        otherbank.setLayout(otherbankLayout);
        otherbankLayout.setHorizontalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payeracctNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerAcctName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payerAcctNameTF)
                    .addComponent(payAcctNumTF)
                    .addComponent(payerBankNoTF)
                    .addComponent(payerBankNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flowNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusTF)
                    .addComponent(prestatusTF)
                    .addComponent(flowNumTF)
                    .addComponent(dataTF, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        otherbankLayout.setVerticalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payeracctNum)
                            .addComponent(payAcctNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerAcctName)
                            .addComponent(payerAcctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flowNum)
                            .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerBankNo)
                            .addComponent(payerBankNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerBankName)
                            .addComponent(payerBankNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prestatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dealInTransaction.add(otherbank);
        otherbank.setBounds(20, 80, 700, 190);

        ourbank.setBackground(new java.awt.Color(255, 255, 255));
        ourbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Our Bank Information"));
        ourbank.setEnabled(false);
        ourbank.setLayout(null);

        payeeAcctNum.setText("Payee Account Num:");
        ourbank.add(payeeAcctNum);
        payeeAcctNum.setBounds(20, 40, 148, 20);

        payeeAcctName.setText("Payee Account Name:");
        ourbank.add(payeeAcctName);
        payeeAcctName.setBounds(20, 80, 160, 20);

        payeeAcctNumTF.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        payeeAcctNumTF.setEnabled(false);
        payeeAcctNumTF.setSelectionColor(new java.awt.Color(0, 255, 0));
        ourbank.add(payeeAcctNumTF);
        payeeAcctNumTF.setBounds(190, 40, 180, 26);

        payeeBankNo.setText("Payee Bank No:");
        ourbank.add(payeeBankNo);
        payeeBankNo.setBounds(20, 120, 150, 20);

        payeeBankName.setText("Payee Bank Name:");
        ourbank.add(payeeBankName);
        payeeBankName.setBounds(20, 160, 140, 20);

        payeeBankNameTF.setEnabled(false);
        ourbank.add(payeeBankNameTF);
        payeeBankNameTF.setBounds(190, 160, 180, 26);

        payeeBankNoTF.setEnabled(false);
        ourbank.add(payeeBankNoTF);
        payeeBankNoTF.setBounds(190, 120, 180, 26);

        payeeAcctNameTF.setEnabled(false);
        ourbank.add(payeeAcctNameTF);
        payeeAcctNameTF.setBounds(190, 80, 180, 26);

        amount.setText("Transaction AMT:");
        ourbank.add(amount);
        amount.setBounds(410, 50, 130, 20);

        amountTF.setEnabled(false);
        ourbank.add(amountTF);
        amountTF.setBounds(540, 50, 140, 26);

        reason.setText("Reason:");
        ourbank.add(reason);
        reason.setBounds(410, 130, 120, 20);

        reasonTF.setEnabled(false);
        ourbank.add(reasonTF);
        reasonTF.setBounds(540, 130, 140, 26);

        currency.setText("Currency:");
        ourbank.add(currency);
        currency.setBounds(410, 90, 120, 20);

        currencyTF.setEnabled(false);
        ourbank.add(currencyTF);
        currencyTF.setBounds(540, 90, 140, 26);

        dealInTransaction.add(ourbank);
        ourbank.setBounds(20, 280, 700, 210);

        dealing.setBackground(new java.awt.Color(255, 255, 255));
        dealing.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Deal with Transaction"));
        dealing.setEnabled(false);

        jLabel13.setText("Deal with Type:");

        dealTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Post  to Account", "Handing to GL Account", "Void Transaction" }));
        dealTypeCB.setEnabled(false);

        postAcctL.setText("Posting Card Num:");

        postCardNoTF.setEnabled(false);

        glAcctL.setText("Gl Account:");

        GLAccountCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80201011234", "80202398345", "80203344987" }));
        GLAccountCB.setEnabled(false);

        acctname.setText("Account Name:");

        postAcctNameTF.setEnabled(false);

        javax.swing.GroupLayout dealingLayout = new javax.swing.GroupLayout(dealing);
        dealing.setLayout(dealingLayout);
        dealingLayout.setHorizontalGroup(
            dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glAcctL, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dealTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GLAccountCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postAcctL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acctname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postCardNoTF)
                    .addComponent(postAcctNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dealingLayout.setVerticalGroup(
            dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dealTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postAcctL)
                    .addComponent(postCardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(glAcctL)
                    .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GLAccountCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acctname)
                        .addComponent(postAcctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dealInTransaction.add(dealing);
        dealing.setBounds(20, 500, 700, 110);

        backButn.setText("Back");
        backButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButnActionPerformed(evt);
            }
        });
        dealInTransaction.add(backButn);
        backButn.setBounds(440, 630, 80, 29);

        okButn.setText("OK");
        okButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButnActionPerformed(evt);
            }
        });
        dealInTransaction.add(okButn);
        okButn.setBounds(560, 630, 93, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dealInTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dealInTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButnActionPerformed

    private void okButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButnActionPerformed
        String setstatus;
        if(CB.equals("Void Transaction")) 
            setstatus = "VOID";
        else 
            setstatus = "POST";
        //update intransaction file
        try{
            Connection con = MySqlConnect.ConnectDB();
            String query = "update intransaction set transactionPreStatus=?, transactionStatus=?, dealType=?, dealPostAcctNo =?, dealDate =?,\n" +
                                "dealTime=?,dealTeller=?  where FlowNum = ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, statusTF.getText());
            st.setString(2, setstatus);
            st.setString(3, CB);
            st.setString(4, postCardNoTF.getText());
            st.setString(5, new SimpleDateFormat("yyyyMMdd").format(Calendar.getInstance().getTime()));
            st.setString(6, new SimpleDateFormat("HHmmss").format(Calendar.getInstance().getTime()));
            st.setString(7, "teller");
            st.setString(8, flowNumTF.getText());
            int result = st.executeUpdate();
            if(result>0){
                JOptionPane.showMessageDialog(null, "Transaction successed !!");
                this.setVisible(false);
               // DealInTransaction.InTransactionPanel.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Transaction failed !!");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        //updat acctinfo file---check acctinfo get the balance and then update
        
        
        if(CB.equals("Post  to Account")){
            double amt = Double.parseDouble(amountTF.getText().toString()) + Double.parseDouble(intrans.originalbalance);
        
            try{
           
                Connection con = MySqlConnect.ConnectDB();       
                String query2 = "update acctinfo set balance = ? where cardNo = ?";
                PreparedStatement st2 = con.prepareStatement(query2);
                st2.setString(1, String.valueOf(amt));
                st2.setString(2, postCardNoTF.getText());
                int result2 = st2.executeUpdate();
                if(result2>0){
                    JOptionPane.showMessageDialog(null, "Card amount changed successfully !!");
                }else{
                    JOptionPane.showMessageDialog(null, "Card amount is not changed!!");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        } 
        
        
    }//GEN-LAST:event_okButnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealInTransactionConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealInTransactionConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealInTransactionConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealInTransactionConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealInTransactionConfirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GLAccountCB;
    private javax.swing.JLabel acctname;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton backButn;
    private javax.swing.JLabel currency;
    private javax.swing.JTextField currencyTF;
    private javax.swing.JTextField dataTF;
    private javax.swing.JLabel date;
    private javax.swing.JPanel dealInTransaction;
    private javax.swing.JComboBox<String> dealTypeCB;
    private javax.swing.JPanel dealing;
    private javax.swing.JLabel flowNum;
    private javax.swing.JTextField flowNumTF;
    private javax.swing.JLabel glAcctL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButn;
    private javax.swing.JPanel otherbank;
    private javax.swing.JPanel ourbank;
    private javax.swing.JTextField payAcctNumTF;
    private javax.swing.JLabel payeeAcctName;
    private javax.swing.JTextField payeeAcctNameTF;
    private javax.swing.JLabel payeeAcctNum;
    private javax.swing.JTextField payeeAcctNumTF;
    private javax.swing.JLabel payeeBankName;
    private javax.swing.JTextField payeeBankNameTF;
    private javax.swing.JLabel payeeBankNo;
    private javax.swing.JTextField payeeBankNoTF;
    private javax.swing.JLabel payerAcctName;
    private javax.swing.JTextField payerAcctNameTF;
    private javax.swing.JLabel payerBankName;
    private javax.swing.JTextField payerBankNameTF;
    private javax.swing.JLabel payerBankNo;
    private javax.swing.JTextField payerBankNoTF;
    private javax.swing.JLabel payeracctNum;
    private javax.swing.JLabel postAcctL;
    private javax.swing.JTextField postAcctNameTF;
    private javax.swing.JTextField postCardNoTF;
    private javax.swing.JTextField prestatusTF;
    private javax.swing.JLabel reason;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JTextField statusTF;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
