/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mypanels.InTransactionPend;

/**
 *
 * @author yangp
 */
public class DealInTransaction extends javax.swing.JFrame {
    InTransactionPend inward;
    public String cardNo;
    public String originalbalance;
    /**
     * Creates new form DealInTransaction
     */
    public DealInTransaction() {
        initComponents();
    }
    
    public DealInTransaction(InTransactionPend p) {
        initComponents();
        inward = p;
        JTable table = inward.gettable();
        String flownum = String.valueOf(table.getModel().getValueAt(table.getSelectedRow(), 0));
         try{
                Connection con = MySqlConnect.ConnectDB();
                String query = "select * from intransaction where flowNum = ?";
                PreparedStatement st = con.prepareStatement(query);
                st.setString(1, flownum);
                ResultSet result = st.executeQuery();
                if(result.next()){
                    payAcctNumTF.setText(result.getString("payerAcctNum"));
                    payerAcctNameTF.setText(result.getString("payerAcctName"));
                    flowNumTF.setText(flownum);
                    dataTF.setText(result.getString("receivedDate"));
                    payerBankNoTF.setText(result.getString("payerBankNo"));
                    payerBankNameTF.setText(result.getString("payerBankName"));
                    payeeAcctNumTF.setText(result.getString("payeeAcctNum"));
                    payeeAcctNameTF.setText(result.getString("payeeAcctName"));
                    payeeBankNoTF.setText(result.getString("payeeBankNo"));
                    payeeBankNameTF.setText(result.getString("payeeBankName"));
                    amountTF.setText(result.getString("transactionAmt"));
                    currencyTF.setText(result.getString("currency"));
                    reasonTF.setText(result.getString("reason"));   
                    prestatusTF.setText(result.getString("transactionPreStatus"));
                    statusTF.setText(result.getString("transactionStatus"));
                }else{
                    JOptionPane.showMessageDialog(null, "NO record is found !");
                }
                
         }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealInTransaction = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        otherbank = new javax.swing.JPanel();
        payeracctNum = new javax.swing.JLabel();
        payerAcctName = new javax.swing.JLabel();
        payerBankNo = new javax.swing.JLabel();
        payerBankName = new javax.swing.JLabel();
        payAcctNumTF = new javax.swing.JTextField();
        payerAcctNameTF = new javax.swing.JTextField();
        payerBankNoTF = new javax.swing.JTextField();
        payerBankNameTF = new javax.swing.JTextField();
        flowNum = new javax.swing.JLabel();
        flowNumTF = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dataTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusTF = new javax.swing.JTextField();
        prestatusTF = new javax.swing.JTextField();
        ourbank = new javax.swing.JPanel();
        payeeAcctNum = new javax.swing.JLabel();
        payeeAcctName = new javax.swing.JLabel();
        payeeAcctNumTF = new javax.swing.JTextField();
        payeeBankNo = new javax.swing.JLabel();
        payeeBankName = new javax.swing.JLabel();
        payeeBankNameTF = new javax.swing.JTextField();
        payeeBankNoTF = new javax.swing.JTextField();
        payeeAcctNameTF = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        reason = new javax.swing.JLabel();
        reasonTF = new javax.swing.JTextField();
        currencyTF = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        dealing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dealTypeCB = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        postCardNumTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        GLAccountCB = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        postAcctNameTF = new javax.swing.JTextField();
        backButn = new javax.swing.JButton();
        nextButn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deal Inward Transaction");
        setBackground(new java.awt.Color(255, 255, 255));

        dealInTransaction.setBackground(new java.awt.Color(255, 255, 255));
        dealInTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        dealInTransaction.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("In-Transaction Pending");
        dealInTransaction.add(title);
        title.setBounds(220, 30, 290, 29);

        otherbank.setBackground(new java.awt.Color(255, 255, 255));
        otherbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Other Bank Information"));
        otherbank.setEnabled(false);

        payeracctNum.setText("Payer Account Num:");

        payerAcctName.setText("Payer Account Name:");

        payerBankNo.setText("Payer Bank No:");

        payerBankName.setText("Payer Bank Name:");

        payAcctNumTF.setEnabled(false);

        payerAcctNameTF.setEnabled(false);

        payerBankNoTF.setEnabled(false);

        payerBankNameTF.setEnabled(false);

        flowNum.setText("Flow Num:");

        flowNumTF.setEnabled(false);

        date.setText("Received Date:");

        dataTF.setEnabled(false);

        jLabel1.setText("Pre Status:");

        jLabel2.setText("Status:");

        statusTF.setEnabled(false);

        prestatusTF.setEnabled(false);

        javax.swing.GroupLayout otherbankLayout = new javax.swing.GroupLayout(otherbank);
        otherbank.setLayout(otherbankLayout);
        otherbankLayout.setHorizontalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payeracctNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerAcctName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payerAcctNameTF)
                    .addComponent(payAcctNumTF)
                    .addComponent(payerBankNoTF)
                    .addComponent(payerBankNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flowNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flowNumTF)
                            .addComponent(dataTF, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prestatusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        otherbankLayout.setVerticalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payeracctNum)
                            .addComponent(payAcctNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerAcctName)
                            .addComponent(payerAcctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flowNum)
                            .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payerBankNo)
                    .addComponent(payerBankNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(prestatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payerBankName)
                    .addComponent(payerBankNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dealInTransaction.add(otherbank);
        otherbank.setBounds(20, 80, 700, 190);

        ourbank.setBackground(new java.awt.Color(255, 255, 255));
        ourbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Our Bank Information"));
        ourbank.setEnabled(false);
        ourbank.setLayout(null);

        payeeAcctNum.setText("Payee Account Num:");
        ourbank.add(payeeAcctNum);
        payeeAcctNum.setBounds(20, 40, 148, 20);

        payeeAcctName.setText("Payee Account Name:");
        ourbank.add(payeeAcctName);
        payeeAcctName.setBounds(20, 80, 160, 20);

        payeeAcctNumTF.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        payeeAcctNumTF.setEnabled(false);
        payeeAcctNumTF.setSelectionColor(new java.awt.Color(0, 255, 0));
        ourbank.add(payeeAcctNumTF);
        payeeAcctNumTF.setBounds(190, 40, 180, 26);

        payeeBankNo.setText("Payee Bank No:");
        ourbank.add(payeeBankNo);
        payeeBankNo.setBounds(20, 120, 150, 20);

        payeeBankName.setText("Payee Bank Name:");
        ourbank.add(payeeBankName);
        payeeBankName.setBounds(20, 160, 140, 20);

        payeeBankNameTF.setEnabled(false);
        ourbank.add(payeeBankNameTF);
        payeeBankNameTF.setBounds(190, 160, 180, 26);

        payeeBankNoTF.setEnabled(false);
        ourbank.add(payeeBankNoTF);
        payeeBankNoTF.setBounds(190, 120, 180, 26);

        payeeAcctNameTF.setEnabled(false);
        ourbank.add(payeeAcctNameTF);
        payeeAcctNameTF.setBounds(190, 80, 180, 26);

        amount.setText("Transaction AMT:");
        ourbank.add(amount);
        amount.setBounds(410, 50, 130, 20);

        amountTF.setEnabled(false);
        ourbank.add(amountTF);
        amountTF.setBounds(540, 50, 140, 26);

        reason.setText("Reason :");
        ourbank.add(reason);
        reason.setBounds(410, 130, 120, 20);

        reasonTF.setEnabled(false);
        ourbank.add(reasonTF);
        reasonTF.setBounds(540, 130, 140, 26);

        currencyTF.setEnabled(false);
        ourbank.add(currencyTF);
        currencyTF.setBounds(540, 90, 140, 26);

        currency.setText("Currency:");
        ourbank.add(currency);
        currency.setBounds(410, 90, 120, 20);

        dealInTransaction.add(ourbank);
        ourbank.setBounds(20, 280, 700, 210);

        dealing.setBackground(new java.awt.Color(255, 255, 255));
        dealing.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Deal with Transaction"));
        dealing.setEnabled(false);

        jLabel13.setText("Deal with Type:");

        dealTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Post  to Account", "Handing to GL Account", "Void Transaction" }));

        jLabel14.setText("Posting Card Num:");

        jLabel15.setText("Gl Account:");

        GLAccountCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80201011234", "80202398345", "80203344987" }));

        jLabel16.setText("Account Name:");

        postAcctNameTF.setEnabled(false);

        javax.swing.GroupLayout dealingLayout = new javax.swing.GroupLayout(dealing);
        dealing.setLayout(dealingLayout);
        dealingLayout.setHorizontalGroup(
            dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dealTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GLAccountCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postCardNumTF)
                    .addComponent(postAcctNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dealingLayout.setVerticalGroup(
            dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dealTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(postCardNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(dealingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GLAccountCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(postAcctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dealInTransaction.add(dealing);
        dealing.setBounds(20, 500, 700, 110);

        backButn.setText("Back");
        backButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButnActionPerformed(evt);
            }
        });
        dealInTransaction.add(backButn);
        backButn.setBounds(440, 630, 80, 29);

        nextButn.setText("Next");
        nextButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButnActionPerformed(evt);
            }
        });
        dealInTransaction.add(nextButn);
        nextButn.setBounds(560, 630, 93, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dealInTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dealInTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButnActionPerformed
        if((dealTypeCB.getSelectedItem().toString()).equals("Post  to Account")){
            
        
        try{
            Connection con = MySqlConnect.ConnectDB();
            String query = "select acctName,balance from acctinfo where cardNo = ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, postCardNumTF.getText());
            ResultSet result = st.executeQuery();
            if(result.next()){
                postAcctNameTF.setText(result.getString("acctName"));
                originalbalance = result.getString("balance");
                DealInTransactionConfirm dealtran = new DealInTransactionConfirm(this);
                dealtran.setVisible(true);
                this.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Posting Card Number is NOT exsit !!");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }else{
                DealInTransactionConfirm dealtran = new DealInTransactionConfirm(this);
                dealtran.setVisible(true);
                this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_nextButnActionPerformed

    private void backButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealInTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealInTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealInTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealInTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealInTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GLAccountCB;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton backButn;
    private javax.swing.JLabel currency;
    private javax.swing.JTextField currencyTF;
    private javax.swing.JTextField dataTF;
    private javax.swing.JLabel date;
    private javax.swing.JPanel dealInTransaction;
    private javax.swing.JComboBox<String> dealTypeCB;
    private javax.swing.JPanel dealing;
    private javax.swing.JLabel flowNum;
    private javax.swing.JTextField flowNumTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextButn;
    private javax.swing.JPanel otherbank;
    private javax.swing.JPanel ourbank;
    private javax.swing.JTextField payAcctNumTF;
    private javax.swing.JLabel payeeAcctName;
    private javax.swing.JTextField payeeAcctNameTF;
    private javax.swing.JLabel payeeAcctNum;
    private javax.swing.JTextField payeeAcctNumTF;
    private javax.swing.JLabel payeeBankName;
    private javax.swing.JTextField payeeBankNameTF;
    private javax.swing.JLabel payeeBankNo;
    private javax.swing.JTextField payeeBankNoTF;
    private javax.swing.JLabel payerAcctName;
    private javax.swing.JTextField payerAcctNameTF;
    private javax.swing.JLabel payerBankName;
    private javax.swing.JTextField payerBankNameTF;
    private javax.swing.JLabel payerBankNo;
    private javax.swing.JTextField payerBankNoTF;
    private javax.swing.JLabel payeracctNum;
    private javax.swing.JTextField postAcctNameTF;
    private javax.swing.JTextField postCardNumTF;
    private javax.swing.JTextField prestatusTF;
    private javax.swing.JLabel reason;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JTextField statusTF;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JTextField getpayacctno(){
        return this.payAcctNumTF;
    }
    public javax.swing.JTextField getpayacctname(){
        return this.payerAcctNameTF;
    }
    public javax.swing.JTextField getflownum(){
        return this.flowNumTF;
    }
    public javax.swing.JTextField getdata(){
        return this.dataTF;
    }
    public javax.swing.JTextField getpaybankno(){
        return this.payerBankNoTF;
    }
    public javax.swing.JTextField getpaybankname(){
        return this.payerBankNameTF;
    }
    public javax.swing.JTextField getpayeeacctno(){
        return this.payeeAcctNumTF;
    }
    public javax.swing.JTextField getpayeeacctname(){
        return this.payeeAcctNameTF;
    }
    public javax.swing.JTextField getpayeebankno(){
        return this.payeeBankNoTF;
    }
    public javax.swing.JTextField getpayeebankname(){
        return this.payeeBankNameTF;
    }
    public javax.swing.JTextField getamount(){
        return this.amountTF;
    }
    public javax.swing.JTextField getcurrency(){
        return this.currencyTF;
    }
    public javax.swing.JTextField getreason(){
        return this.reasonTF;
    }
    public javax.swing.JTextField getprestatus(){
        return this.prestatusTF;
    }
    public javax.swing.JTextField getstatus(){
        return this.statusTF;
    }
     public javax.swing.JTextField getpostacctno(){
        return this.postCardNumTF;
    }
      public javax.swing.JTextField getpostacctname(){
        return this.postAcctNameTF;
    }
     public javax.swing.JComboBox<String>  getdealtype(){
        return this.dealTypeCB;
    }
    
}
