/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.awt.GridBagConstraints;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import mypanels.CancelAcct;
import mypanels.DepositC;
import mypanels.DepositConfirm;
import mypanels.InTransactionPend;
import mypanels.OpenAcct;
import mypanels.QueryAccountInformation;
import mypanels.QueryInTransaction;
import mypanels.QueryOutTransaction;
import mypanels.RemoveReportLoss;
import mypanels.ReportLoss;
import mypanels.TransferOtherB;
import mypanels.TransferSameB;
import mypanels.Withdraw;

/**
 *
 * @author yangp
 */
public class MainScreen extends javax.swing.JFrame {
    static String teller = null;
    
   ///initialize other screen 
    DepositC depositscreen ;
    OpenAcct openacctscreen ;
    CancelAcct cancelacctscreen ;
    ReportLoss reportlossscreen;
    RemoveReportLoss removelossscreen ;
    Withdraw withdrawscreen ;
    TransferSameB sbtransferscreen ;
    TransferOtherB obtransferscreen ;
    InTransactionPend inwardscreen ;
    QueryAccountInformation queryinforscreen = new QueryAccountInformation();
    QueryInTransaction queryinscreen ;
    QueryOutTransaction queryoutscreen ;
    
    /**
     * Creates new form MainScreen
     */
     public MainScreen() {
        initComponents();
     }
    public MainScreen(String teller) {
        initComponents();
        this.teller = teller;
        tellerId.setText(this.teller);
        dateLB.setText( new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime()));
        timeLB.setText(new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime()));
        int day = Calendar.getInstance().get(Calendar.DAY_OF_WEEK);
        switch(day){
            case 2: ddLB.setText("Monday");break;
            case 3: ddLB.setText("Tuesday");break;
            case 4: ddLB.setText("Wednesdays");break;
            case 5: ddLB.setText("Thursday"); break;
            case 6: ddLB.setText("Friday"); break;
            case 7: ddLB.setText("Saturday");break;
            case 8: ddLB.setText("Sunday"); break;
        }
        
       // openacctscreen  = new OpenAcct(this.teller);
      //  depositscreen.setVisible(false);
      //  openacctscreen = new OpenAcct(this.teller);
     //   openacctscreen.setVisible(false);
      //  cancelacctscreen = new CancelAcct();
      //  cancelacctscreen.setVisible(false);
       // reportlossscreen.setVisible(false);
      //  removelossscreen.setVisible(false);
       // withdrawscreen.setVisible(false);
       // sbtransferscreen.setVisible(false);
        //obtransferscreen.setVisible(false);
       // inwardscreen.setVisible(false);
       // queryinforscreen.setVisible(false);
       // queryinscreen.setVisible(false);
       // queryoutscreen.setVisible(false);
      
        try{
        Connection con  = MySqlConnect.ConnectDB(); 
        String query = "select tellName from tellerinfo where tellID = ?";
        PreparedStatement st = con.prepareStatement(query);
        st.setString(1, this.teller);
        ResultSet result  = st.executeQuery();
        if(result.next()){
            tellerNameLB.setText(result.getString("tellName"));
        }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
        }
        
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholebackPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        ddLB = new javax.swing.JLabel();
        timeLB = new javax.swing.JLabel();
        dateLB = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bankimage = new javax.swing.JLabel();
        tellerId = new javax.swing.JLabel();
        tellerNameLB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        functionTree = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        functionbodyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Function Screen");
        setResizable(false);

        wholebackPanel.setBackground(new java.awt.Color(255, 255, 255));
        wholebackPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wholebackPanel.setLayout(null);

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ddLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        timeLB.setText("6:11 PM");

        dateLB.setText("6/18/2016");

        title.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        title.setText("Welcome to Bank of China");

        bankimage.setIcon(new javax.swing.ImageIcon("C:\\jave exercise\\MyBankSystem\\photo\\bank3.jpg")); // NOI18N

        tellerId.setBackground(new java.awt.Color(255, 255, 255));
        tellerId.setFont(tellerId.getFont().deriveFont(tellerId.getFont().getSize()+1f));
        tellerId.setText("JBC80025 ");

        tellerNameLB.setText("haha");

        jLabel2.setText("-");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bankimage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(tellerId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tellerNameLB)))
                .addGap(79, 79, 79)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLB))
                        .addGap(30, 30, 30))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addComponent(ddLB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addComponent(bankimage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tellerId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tellerNameLB)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(ddLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLB)
                        .addGap(8, 8, 8))))
        );

        wholebackPanel.add(titlePanel);
        titlePanel.setBounds(0, 0, 740, 120);

        functionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        functionPanel.setLayout(null);

        functionTree.setFont(functionTree.getFont().deriveFont(functionTree.getFont().getSize()+1f));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bank system");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Account Management");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Open an account");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Cancel an account");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Report for loss");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Remove of reported loss");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Checking Account");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Cash");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Deposit");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Cash withdraw");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Positive Reverse");
        treeNode4.add(treeNode5);
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("Nagative Reverse");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Card");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Check");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Transfer");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Same Bank");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Other Bank");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Received Transaction");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Deal Transaction");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Loan Transaction");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Query Information");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Account information");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Inward Transaction Query");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Outward Transaction Query");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Reverse Transaction details");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Quit Bank System");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Bank reconciliation");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Quit");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        functionTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        functionTree.setToolTipText("");
        functionTree.setRootVisible(false);
        functionTree.setShowsRootHandles(true);
        functionTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                functionTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(functionTree);

        functionPanel.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 200, 570);

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        functionPanel.add(jButton1);
        jButton1.setBounds(70, 210, 93, 29);

        wholebackPanel.add(functionPanel);
        functionPanel.setBounds(0, 120, 200, 570);

        functionbodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        functionbodyPanel.setEnabled(false);
        functionbodyPanel.setLayout(null);
        wholebackPanel.add(functionbodyPanel);
        functionbodyPanel.setBounds(200, 120, 540, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholebackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholebackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void functionTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_functionTreeMouseClicked
        DefaultTreeModel mode = (DefaultTreeModel) functionTree.getModel();
        DefaultMutableTreeNode selectednode = (DefaultMutableTreeNode) functionTree.getLastSelectedPathComponent();
       switch(selectednode.toString()){
           case("Open an account"):  
              
               { 
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   openacctscreen = new OpenAcct(this.teller);
                   functionbodyPanel.add(openacctscreen); 
                   openacctscreen.setVisible(true); 
                   openacctscreen.getpanel().setVisible(true);
                   functionbodyPanel.repaint(); 
               }
               break;
           case("Cancel an account"):
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   cancelacctscreen = new CancelAcct();
                   functionbodyPanel.add(cancelacctscreen);
                   cancelacctscreen.setVisible(true);
                   cancelacctscreen.getmainpanel().setVisible(true);  
                   functionbodyPanel.revalidate();
                   functionbodyPanel.repaint(); 
                   
               }
               break;
          case("Report for loss"):
             
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   reportlossscreen  = new ReportLoss();
                   functionbodyPanel.add(reportlossscreen);                     
                   reportlossscreen.setVisible(true); 
                   reportlossscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   functionbodyPanel.repaint(); 
               }
               break;
           case("Remove of reported loss"):
              
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   removelossscreen = new RemoveReportLoss();
                   functionbodyPanel.add(removelossscreen);                     
                   removelossscreen.setVisible(true); 
                   removelossscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   removelossscreen.repaint(); 
               }
               break;
           case("Deposit"):
               
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   depositscreen = new DepositC();
                   functionbodyPanel.add(depositscreen);                     
                   depositscreen.setVisible(true); 
                   functionbodyPanel.revalidate();
                   functionbodyPanel.repaint(); 
               }
               break;
           case("Cash withdraw"):
            
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   withdrawscreen = new Withdraw();
                   functionbodyPanel.add(withdrawscreen);                     
                   withdrawscreen.setVisible(true); 
                   withdrawscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   withdrawscreen.repaint(); 
               }
               break;
           case("Same Bank"):
              
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   sbtransferscreen = new TransferSameB();
                   functionbodyPanel.add(sbtransferscreen);                     
                   sbtransferscreen.setVisible(true); 
                   sbtransferscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   sbtransferscreen.repaint(); 
               }
               break;
               
           case("Other Bank"):
              
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   obtransferscreen = new TransferOtherB();
                   functionbodyPanel.add(obtransferscreen);                     
                   obtransferscreen.setVisible(true); 
                   obtransferscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   obtransferscreen.repaint(); 
               }
               break;
           case("Deal Transaction"):
               
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   inwardscreen = new InTransactionPend();
                   functionbodyPanel.add(inwardscreen);                     
                   inwardscreen.setVisible(true); 
                   inwardscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   inwardscreen.repaint(); 
               }
               break;
               
          case("Account information"):
               if(queryinforscreen != null)
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
   
                   functionbodyPanel.add(queryinforscreen);                     
                   queryinforscreen.setVisible(true); 
                   queryinforscreen.getmainpanel().setVisible(true);
                   queryinforscreen.repaint(); 
               }
               break;
          case("Inward Transaction Query"):
               
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   queryinscreen = new QueryInTransaction();
                   functionbodyPanel.add(queryinscreen);                     
                   queryinscreen.setVisible(true); 
                   queryinscreen.getmainpanel().setVisible(true);
                 //  queryinscreen.gettable().setVisible(true);
                   functionbodyPanel.revalidate();
                   queryinscreen.repaint(); 
               }
               break;
          case("Outward Transaction Query"):
             
               {
                   functionbodyPanel.removeAll();
                   functionbodyPanel.setLayout(new java.awt.BorderLayout());
                   queryoutscreen = new QueryOutTransaction();
                   functionbodyPanel.add(queryoutscreen);                     
                   queryoutscreen.setVisible(true); 
                   queryoutscreen.getmainpanel().setVisible(true);
                   functionbodyPanel.revalidate();
                   queryoutscreen.repaint(); 
               }
               break;
               
               
       }

        
    }//GEN-LAST:event_functionTreeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankimage;
    private javax.swing.JLabel dateLB;
    private javax.swing.JLabel ddLB;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JTree functionTree;
    private javax.swing.JPanel functionbodyPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tellerId;
    private javax.swing.JLabel tellerNameLB;
    private javax.swing.JLabel timeLB;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel wholebackPanel;
    // End of variables declaration//GEN-END:variables

       
}
