/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import mypanels.OpenAcct;

/**
 *
 * @author yangp
 */
public class OpenAcctConfirm extends javax.swing.JFrame {
    OpenAcct openacct;
    Connection con = null ;
    PreparedStatement st = null;
    int result ;
    String tellerID;

    /**
     * Creates new form OpenAcctConfirm
     */
    public OpenAcctConfirm() {
        initComponents();
    }
    
     public OpenAcctConfirm(OpenAcct o) {
        initComponents();
        openacct = o;
        tellerID = openacct.teller;
        appliNameTF.setText((openacct.getappliNameTF()).getText());
        phoneNumTF.setText(openacct.getphoneNumTF().getText());
        countryTF.setText(openacct.getcountryTF().getText());
        addressTF.setText(openacct.getaddressTF().getText());
        idTypeCB.setSelectedItem(openacct.getidTypeCB().getSelectedItem());
        idNumTF.setText(openacct.getidNumTF().getText());
        cardNumTF.setText(openacct.getcardNumTF().getText());
        accNumTF.setText(openacct.getaccNumTF().getText());
        remarkTA.setText(openacct.getremarkTA().getText());
        acctTypeCB.setSelectedItem(openacct.getacctTypeCB().getSelectedItem());
        cardTypeCB.setSelectedItem(openacct.getcardTypeCB().getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openacctConfirm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NameLB = new javax.swing.JLabel();
        appliNameTF = new javax.swing.JTextField();
        addressLB = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        phoneNumLB = new javax.swing.JLabel();
        phoneNumTF = new javax.swing.JTextField();
        countryLB = new javax.swing.JLabel();
        countryTF = new javax.swing.JTextField();
        idTypeLB = new javax.swing.JLabel();
        idTypeCB = new javax.swing.JComboBox<>();
        idNumLB = new javax.swing.JLabel();
        idNumTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cardNumLB = new javax.swing.JLabel();
        cardNumTF = new javax.swing.JTextField();
        accNumLB = new javax.swing.JLabel();
        accNumTF = new javax.swing.JTextField();
        remarkLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarkTA = new javax.swing.JTextArea();
        passwordLB = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        cardType = new javax.swing.JLabel();
        acctType = new javax.swing.JLabel();
        cardTypeCB = new javax.swing.JComboBox<>();
        acctTypeCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        titleLB = new javax.swing.JLabel();
        backButn = new javax.swing.JButton();
        EnterButn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open an Account Confirm Screen");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(744, 692));
        getContentPane().setLayout(null);

        openacctConfirm.setBackground(new java.awt.Color(255, 255, 255));
        openacctConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        openacctConfirm.setMinimumSize(new java.awt.Dimension(0, 0));
        openacctConfirm.setPreferredSize(new java.awt.Dimension(744, 692));
        openacctConfirm.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Applicatnt Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        NameLB.setText("Name:");
        jPanel1.add(NameLB);
        NameLB.setBounds(10, 40, 47, 20);

        appliNameTF.setEnabled(false);
        appliNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(appliNameTF);
        appliNameTF.setBounds(130, 40, 130, 26);

        addressLB.setText("Address:");
        jPanel1.add(addressLB);
        addressLB.setBounds(10, 160, 70, 20);

        addressTF.setToolTipText("Address1");
        addressTF.setEnabled(false);
        jPanel1.add(addressTF);
        addressTF.setBounds(130, 160, 390, 26);

        phoneNumLB.setText("Phone Num:");
        jPanel1.add(phoneNumLB);
        phoneNumLB.setBounds(10, 80, 90, 20);

        phoneNumTF.setEnabled(false);
        jPanel1.add(phoneNumTF);
        phoneNumTF.setBounds(130, 80, 130, 26);

        countryLB.setText("Home Country:");
        jPanel1.add(countryLB);
        countryLB.setBounds(10, 120, 120, 20);

        countryTF.setEnabled(false);
        jPanel1.add(countryTF);
        countryTF.setBounds(130, 120, 130, 26);

        idTypeLB.setText("ID type:");
        jPanel1.add(idTypeLB);
        idTypeLB.setBounds(290, 30, 70, 20);

        idTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Social Security Card", "Passport", " ", " " }));
        idTypeCB.setEnabled(false);
        jPanel1.add(idTypeCB);
        idTypeCB.setBounds(350, 30, 170, 26);

        idNumLB.setText("ID Num:");
        jPanel1.add(idNumLB);
        idNumLB.setBounds(290, 70, 70, 20);

        idNumTF.setEnabled(false);
        jPanel1.add(idNumTF);
        idNumTF.setBounds(360, 70, 160, 26);

        openacctConfirm.add(jPanel1);
        jPanel1.setBounds(30, 90, 610, 200);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Card Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setEnabled(false);
        jPanel2.setLayout(null);

        cardNumLB.setText("Card Num:");
        jPanel2.add(cardNumLB);
        cardNumLB.setBounds(10, 30, 90, 20);

        cardNumTF.setEnabled(false);
        cardNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumTFActionPerformed(evt);
            }
        });
        jPanel2.add(cardNumTF);
        cardNumTF.setBounds(130, 30, 240, 26);

        accNumLB.setText("Account Num:");
        jPanel2.add(accNumLB);
        accNumLB.setBounds(10, 60, 110, 20);

        accNumTF.setEnabled(false);
        jPanel2.add(accNumTF);
        accNumTF.setBounds(130, 60, 240, 26);

        remarkLB.setText("Remark: ");
        jPanel2.add(remarkLB);
        remarkLB.setBounds(10, 140, 80, 20);

        remarkTA.setColumns(20);
        remarkTA.setRows(5);
        remarkTA.setEnabled(false);
        jScrollPane1.setViewportView(remarkTA);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 120, 300, 60);

        passwordLB.setText("Password:");
        jPanel2.add(passwordLB);
        passwordLB.setBounds(10, 100, 80, 20);
        jPanel2.add(passwordTF);
        passwordTF.setBounds(130, 90, 240, 26);

        cardType.setText("Card Type:");
        jPanel2.add(cardType);
        cardType.setBounds(390, 30, 80, 20);

        acctType.setText("Acct Type:");
        jPanel2.add(acctType);
        acctType.setBounds(390, 60, 76, 20);

        cardTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit Card", "Credit Card" }));
        cardTypeCB.setEnabled(false);
        jPanel2.add(cardTypeCB);
        cardTypeCB.setBounds(470, 30, 130, 26);

        acctTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving Acct", "Checking Acct" }));
        acctTypeCB.setEnabled(false);
        jPanel2.add(acctTypeCB);
        acctTypeCB.setBounds(470, 60, 130, 26);

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("*");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 110, 20, 10);

        openacctConfirm.add(jPanel2);
        jPanel2.setBounds(30, 300, 610, 190);

        titleLB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLB.setText("Open an Account");
        titleLB.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        titleLB.setMinimumSize(new java.awt.Dimension(0, 0));
        openacctConfirm.add(titleLB);
        titleLB.setBounds(230, 40, 210, 40);

        backButn.setText("Back");
        backButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButnActionPerformed(evt);
            }
        });
        openacctConfirm.add(backButn);
        backButn.setBounds(410, 530, 90, 40);

        EnterButn.setText("Enter");
        EnterButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButnActionPerformed(evt);
            }
        });
        openacctConfirm.add(EnterButn);
        EnterButn.setBounds(540, 530, 90, 40);

        getContentPane().add(openacctConfirm);
        openacctConfirm.setBounds(-10, 0, 760, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appliNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appliNameTFActionPerformed

    private void cardNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumTFActionPerformed

    private void backButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButnActionPerformed
        openacct.setEnableRec(openacct.getpanel(),true);
        this.setVisible(false);
    }//GEN-LAST:event_backButnActionPerformed

    private void EnterButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButnActionPerformed
       //CHECK THE PASSWORD FEILD
       if((String.valueOf(passwordTF.getPassword())).equals("")){
           JOptionPane.showMessageDialog(null, "Password is missing !\n please enter password and try again!","Warning",JOptionPane.OK_OPTION);
       }
       else{
        this.setVisible(false);
        openacct.setEnableRec(openacct.getpanel(),true);
        openacct.getpanel().setVisible(false);
        String name = appliNameTF.getText();
        String idType = String.valueOf(idTypeCB.getSelectedItem());
        String phone = phoneNumTF.getText();
        String idNum = idNumTF.getText();
        String country = countryTF.getText();
        String address = addressTF.getText();
        String cardNum = cardNumTF.getText();
        String acctNum = accNumTF.getText();
        String typeCard = String.valueOf(cardTypeCB.getSelectedItem());
        String typeAcct = String.valueOf(acctTypeCB.getSelectedItem());
        String password = String.valueOf(passwordTF.getPassword());
        String remark = remarkTA.getText();
        try{ 
            con = MySqlConnect.ConnectDB(); 
            String query = "insert into acctinfo values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            st = con.prepareStatement(query);
            st.setString(1,acctNum );
            st.setString(2, name);
            st.setString(3, cardNum);
            st.setString(4, "Valid");
            st.setString(5, "Valid");
            st.setString(6, typeAcct);
            st.setString(7, typeCard);
            st.setString(8, password);
            st.setDouble(9, 0);
            st.setString(10,null);
            st.setString(11, idType);
            st.setString(12, idNum);
            st.setString(13, phone);
            st.setString(14, address);
            st.setString(15, country);
            st.setString(16, remark);
            st.setString(17,null);
            st.setString(18,null);
            st.setString(19,null);
            st.setString(20, new SimpleDateFormat("yyyyMMdd").format(Calendar.getInstance().getTime()));
            st.setString(21, new SimpleDateFormat("HHmmss").format(Calendar.getInstance().getTime()));
            st.setString(22, tellerID);
            
            result = st.executeUpdate();
            if( result > 0){
               JOptionPane.showMessageDialog(null, "Date is saved! Transaction is successful! ");
            }
            else{
                JOptionPane.showMessageDialog(null, "Date is NOT saved! Transaction is failed! ", "Fail",JOptionPane.ERROR_MESSAGE);
           }
         
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Transaction is failed! \n" + ex);
           
        }
    }//GEN-LAST:event_EnterButnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenAcctConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenAcctConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenAcctConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenAcctConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenAcctConfirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButn;
    private javax.swing.JLabel NameLB;
    private javax.swing.JLabel accNumLB;
    private javax.swing.JTextField accNumTF;
    private javax.swing.JLabel acctType;
    private javax.swing.JComboBox<String> acctTypeCB;
    private javax.swing.JLabel addressLB;
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField appliNameTF;
    private javax.swing.JButton backButn;
    private javax.swing.JLabel cardNumLB;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JLabel cardType;
    private javax.swing.JComboBox<String> cardTypeCB;
    private javax.swing.JLabel countryLB;
    private javax.swing.JTextField countryTF;
    private javax.swing.JLabel idNumLB;
    private javax.swing.JTextField idNumTF;
    private javax.swing.JComboBox<String> idTypeCB;
    private javax.swing.JLabel idTypeLB;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel openacctConfirm;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel phoneNumLB;
    private javax.swing.JTextField phoneNumTF;
    private javax.swing.JLabel remarkLB;
    private javax.swing.JTextArea remarkTA;
    private javax.swing.JLabel titleLB;
    // End of variables declaration//GEN-END:variables
}
