/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mypanels.CancelAcct;

/**
 *
 * @author yangp
 */
public class QueryAcctInfo extends javax.swing.JFrame {
    
    CancelAcct listscreen;
    /**
     * Creates new form QueryAcctInfo
     */
    public QueryAcctInfo() {
        initComponents();
    }
    
    public QueryAcctInfo(CancelAcct acct) {
        initComponents();
        listscreen = acct;
        
        JTable table = listscreen.gettable();
        String aNum = String.valueOf(table.getModel().getValueAt(table.getSelectedRow(), 0));
        acctNumTF.setText(aNum);
        String cNum = String.valueOf(table.getModel().getValueAt(table.getSelectedRow(), 1));
        cardNumTF.setText(cNum);
        String aName = String.valueOf(table.getModel().getValueAt(table.getSelectedRow(), 2));
        acctNameTF.setText(aName);
         try{
           
             Connection con = MySqlConnect.ConnectDB(); 
             String query = "select acctType,cardType,cardStatus,acctStatus,applicantIDNum,applicantIDType,applicantPhone,applicantAddress, balance,currency\n" +
                                " from acctinfo where acctNo = ? and acctName = ? and cardNo = ?";
              PreparedStatement st = con.prepareStatement(query);
              st.setString(1, aNum);
              st.setString(2, aName);
              st.setString(3, cNum);
              ResultSet result = st.executeQuery();
              
              if(result.next()){
                   acctTypeTF.setText(result.getString("acctType"));
                   cardTypeTF.setText(result.getString("cardType"));
                   cardStatus.setText(result.getString("cardStatus"));
                   acctStatus.setText(result.getString("acctStatus"));
                   balanceTF.setText(result.getString("balance"));
                   currencyTF.setText(result.getString("currency"));
                   
                   phoneNumTF.setText(result.getString("applicantPhone"));
                   addressTF.setText(result.getString("applicantAddress"));
                   idTypeTF.setText(result.getString("applicantIDType"));
                   idNumTF.setText(result.getString("applicantIDNum"));
              }
             
              
              
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Search data failed! \n" + ex);
        }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showDetailPanel = new javax.swing.JPanel();
        AcctInfo = new javax.swing.JPanel();
        cardNum = new javax.swing.JLabel();
        AcctNum = new javax.swing.JLabel();
        cardType = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        cardTypeTF = new javax.swing.JTextField();
        cardNumTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        currencyTF = new javax.swing.JTextField();
        acctName = new javax.swing.JLabel();
        acctNumTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        acctTypeTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cardStatus = new javax.swing.JTextField();
        acctNameTF = new javax.swing.JTextField();
        balance = new javax.swing.JLabel();
        currency = new javax.swing.JLabel();
        acctStatus = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        idTypeTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idNumTF = new javax.swing.JTextField();
        phoneNumL = new javax.swing.JLabel();
        adressL = new javax.swing.JLabel();
        phoneNumTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        okButn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account Detail Information");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(620, 650));
        setResizable(false);

        showDetailPanel.setBackground(new java.awt.Color(255, 255, 255));
        showDetailPanel.setPreferredSize(new java.awt.Dimension(650, 650));
        showDetailPanel.setLayout(null);

        AcctInfo.setBackground(new java.awt.Color(255, 255, 255));
        AcctInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Account Information"));
        AcctInfo.setEnabled(false);
        AcctInfo.setLayout(null);

        cardNum.setText("Card Num:");
        AcctInfo.add(cardNum);
        cardNum.setBounds(20, 40, 78, 20);

        AcctNum.setText("Account Num:");
        AcctInfo.add(AcctNum);
        AcctNum.setBounds(20, 80, 102, 20);

        cardType.setText("Card Type:");
        AcctInfo.add(cardType);
        cardType.setBounds(300, 50, 80, 20);

        balanceTF.setEnabled(false);
        AcctInfo.add(balanceTF);
        balanceTF.setBounds(130, 160, 160, 26);

        cardTypeTF.setEnabled(false);
        AcctInfo.add(cardTypeTF);
        cardTypeTF.setBounds(390, 40, 110, 26);

        cardNumTF.setEnabled(false);
        AcctInfo.add(cardNumTF);
        cardNumTF.setBounds(130, 40, 160, 26);

        jLabel8.setText("Acct Type:");
        AcctInfo.add(jLabel8);
        jLabel8.setBounds(300, 80, 80, 20);

        currencyTF.setEnabled(false);
        AcctInfo.add(currencyTF);
        currencyTF.setBounds(130, 200, 160, 26);

        acctName.setText("Account Name:");
        AcctInfo.add(acctName);
        acctName.setBounds(20, 120, 109, 20);

        acctNumTF.setEnabled(false);
        AcctInfo.add(acctNumTF);
        acctNumTF.setBounds(130, 80, 160, 26);

        jLabel10.setText("Acct Status:");
        AcctInfo.add(jLabel10);
        jLabel10.setBounds(300, 160, 90, 20);

        acctTypeTF.setEnabled(false);
        AcctInfo.add(acctTypeTF);
        acctTypeTF.setBounds(390, 80, 110, 26);

        jLabel11.setText("Card Status:");
        AcctInfo.add(jLabel11);
        jLabel11.setBounds(300, 120, 90, 20);

        cardStatus.setEnabled(false);
        AcctInfo.add(cardStatus);
        cardStatus.setBounds(390, 120, 110, 26);

        acctNameTF.setEnabled(false);
        AcctInfo.add(acctNameTF);
        acctNameTF.setBounds(130, 120, 160, 26);

        balance.setText("Balance:");
        AcctInfo.add(balance);
        balance.setBounds(20, 160, 59, 20);

        currency.setText("Currency:");
        AcctInfo.add(currency);
        currency.setBounds(20, 200, 80, 20);

        acctStatus.setEnabled(false);
        AcctInfo.add(acctStatus);
        acctStatus.setBounds(390, 160, 110, 26);

        showDetailPanel.add(AcctInfo);
        AcctInfo.setBounds(40, 80, 520, 260);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Account  Detail  Information ");
        showDetailPanel.add(title);
        title.setBounds(110, 30, 360, 29);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Applicant Information"));
        jPanel1.setEnabled(false);

        jLabel13.setText("ID type:");

        idTypeTF.setEnabled(false);

        jLabel12.setText("ID Num:");

        idNumTF.setEnabled(false);

        phoneNumL.setText("Phone Num:");

        adressL.setText("Address:");

        phoneNumTF.setEnabled(false);

        addressTF.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adressL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneNumL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(idNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(idNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumL)
                    .addComponent(phoneNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressL)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        showDetailPanel.add(jPanel1);
        jPanel1.setBounds(40, 340, 520, 210);

        okButn.setText("OK");
        okButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButnActionPerformed(evt);
            }
        });
        showDetailPanel.add(okButn);
        okButn.setBounds(423, 560, 120, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButnActionPerformed
        this.setVisible(false);
        listscreen.setEnableRec(listscreen.getmainpanel(),true);
    }//GEN-LAST:event_okButnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryAcctInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryAcctInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryAcctInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryAcctInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryAcctInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AcctInfo;
    private javax.swing.JLabel AcctNum;
    private javax.swing.JLabel acctName;
    private javax.swing.JTextField acctNameTF;
    private javax.swing.JTextField acctNumTF;
    private javax.swing.JTextField acctStatus;
    private javax.swing.JTextField acctTypeTF;
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel adressL;
    private javax.swing.JLabel balance;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JLabel cardNum;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JTextField cardStatus;
    private javax.swing.JLabel cardType;
    private javax.swing.JTextField cardTypeTF;
    private javax.swing.JLabel currency;
    private javax.swing.JTextField currencyTF;
    private javax.swing.JTextField idNumTF;
    private javax.swing.JTextField idTypeTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButn;
    private javax.swing.JLabel phoneNumL;
    private javax.swing.JTextField phoneNumTF;
    private javax.swing.JPanel showDetailPanel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
