/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mybanksystem;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mypanels.QueryInTransaction;

/**
 *
 * @author yangp
 */
public class ShowDetailIn extends javax.swing.JFrame {
    QueryInTransaction inquery;
    /**
     * Creates new form ShowDetail
     */
    public ShowDetailIn() {
        initComponents();
    }
    
    public ShowDetailIn(QueryInTransaction data) {
        initComponents();
        inquery = data;
        JTable table = inquery.gettable();
        String flownum = String.valueOf(table.getModel().getValueAt(table.getSelectedRow(), 0));
        try{
                Connection con = MySqlConnect.ConnectDB();
                String query = "select * from intransaction where flowNum = ?";
                PreparedStatement st = con.prepareStatement(query);
                st.setString(1, flownum);
                ResultSet result = st.executeQuery();
                if(result.next()){
                    payAcctNumTF.setText(result.getString("payerAcctNum"));
                    payerAcctNameTF.setText(result.getString("payerAcctName"));
                    payerBankNoTF.setText(result.getString("payerBankNo"));
                    payerBankNameTF.setText(result.getString("payerBankName"));
                    amountTF.setText(result.getString("transactionAmt"));
                    currencyTF.setText(result.getString("currency"));
                    reasonTF.setText(result.getString("reason"));   
                    
                    flowNumTF.setText(flownum);
                    dataTF.setText(result.getString("receivedDate"));
                    
                    payeeAcctNumTF.setText(result.getString("payeeAcctNum"));
                    payeeAcctNameTF.setText(result.getString("payeeAcctName"));
                    payeeBankNoTF.setText(result.getString("payeeBankNo"));
                    payeeBankNameTF.setText(result.getString("payeeBankName"));
                    prestatusTF.setText(result.getString("transactionPreStatus"));
                    statusTF.setText(result.getString("transactionStatus"));
                    dealingTellerTF.setText(result.getString("dealTeller"));
                }else{
                    JOptionPane.showMessageDialog(null, "NO record is found !");
                }
                
         }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showDetailPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        otherbank = new javax.swing.JPanel();
        payeracctNum = new javax.swing.JLabel();
        payerAcctName = new javax.swing.JLabel();
        payerBankNo = new javax.swing.JLabel();
        payerBankName = new javax.swing.JLabel();
        payAcctNumTF = new javax.swing.JTextField();
        payerAcctNameTF = new javax.swing.JTextField();
        payerBankNoTF = new javax.swing.JTextField();
        payerBankNameTF = new javax.swing.JTextField();
        flowNum = new javax.swing.JLabel();
        flowNumTF = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dataTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prestatusTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statusTF = new javax.swing.JTextField();
        ourbank = new javax.swing.JPanel();
        payeeAcctNum = new javax.swing.JLabel();
        payeeAcctName = new javax.swing.JLabel();
        payeeAcctNumTF = new javax.swing.JTextField();
        payeeBankNo = new javax.swing.JLabel();
        payeeBankName = new javax.swing.JLabel();
        payeeBankNameTF = new javax.swing.JTextField();
        payeeBankNoTF = new javax.swing.JTextField();
        payeeAcctNameTF = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        currency = new javax.swing.JLabel();
        currencyTF = new javax.swing.JTextField();
        reason = new javax.swing.JLabel();
        reasonTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dealingTellerTF = new javax.swing.JTextField();
        reviewTellerTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction Details ");
        setBackground(new java.awt.Color(255, 255, 255));

        showDetailPanel.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Transaction Details");

        otherbank.setBackground(new java.awt.Color(255, 255, 255));
        otherbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Other Bank Information"));
        otherbank.setEnabled(false);

        payeracctNum.setText("Payer Account Num:");

        payerAcctName.setText("Payer Account Name:");

        payerBankNo.setText("Payer Bank No:");

        payerBankName.setText("Payer Bank Name:");

        payAcctNumTF.setEnabled(false);

        payerAcctNameTF.setEnabled(false);

        payerBankNoTF.setEnabled(false);

        payerBankNameTF.setEnabled(false);

        flowNum.setText("Flow Num:");

        flowNumTF.setEnabled(false);

        date.setText("Received Date:");

        dataTF.setEnabled(false);

        jLabel3.setText("Pre Status:");

        prestatusTF.setEnabled(false);

        jLabel4.setText("Status:");

        statusTF.setEnabled(false);

        javax.swing.GroupLayout otherbankLayout = new javax.swing.GroupLayout(otherbank);
        otherbank.setLayout(otherbankLayout);
        otherbankLayout.setHorizontalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payeracctNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerAcctName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payerBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payerAcctNameTF)
                    .addComponent(payAcctNumTF)
                    .addComponent(payerBankNoTF)
                    .addComponent(payerBankNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(flowNum, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prestatusTF))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statusTF)))
                .addGap(3, 3, 3))
        );
        otherbankLayout.setVerticalGroup(
            otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherbankLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(otherbankLayout.createSequentialGroup()
                                .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(flowNum)
                                    .addComponent(flowNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(date)
                                .addComponent(dataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(prestatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(otherbankLayout.createSequentialGroup()
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payeracctNum)
                            .addComponent(payAcctNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerAcctName)
                            .addComponent(payerAcctNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerBankNo)
                            .addComponent(payerBankNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payerBankName)
                            .addComponent(payerBankNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ourbank.setBackground(new java.awt.Color(255, 255, 255));
        ourbank.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Our Bank Information"));
        ourbank.setEnabled(false);
        ourbank.setLayout(null);

        payeeAcctNum.setText("Payee Account Num:");
        ourbank.add(payeeAcctNum);
        payeeAcctNum.setBounds(20, 40, 148, 20);

        payeeAcctName.setText("Payee Account Name:");
        ourbank.add(payeeAcctName);
        payeeAcctName.setBounds(20, 80, 160, 20);

        payeeAcctNumTF.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        payeeAcctNumTF.setEnabled(false);
        payeeAcctNumTF.setSelectionColor(new java.awt.Color(0, 255, 0));
        ourbank.add(payeeAcctNumTF);
        payeeAcctNumTF.setBounds(190, 40, 180, 26);

        payeeBankNo.setText("Payee Bank No:");
        ourbank.add(payeeBankNo);
        payeeBankNo.setBounds(20, 120, 150, 20);

        payeeBankName.setText("Payee Bank Name:");
        ourbank.add(payeeBankName);
        payeeBankName.setBounds(20, 160, 140, 20);

        payeeBankNameTF.setEnabled(false);
        ourbank.add(payeeBankNameTF);
        payeeBankNameTF.setBounds(190, 160, 180, 26);

        payeeBankNoTF.setEnabled(false);
        ourbank.add(payeeBankNoTF);
        payeeBankNoTF.setBounds(190, 120, 180, 26);

        payeeAcctNameTF.setEnabled(false);
        ourbank.add(payeeAcctNameTF);
        payeeAcctNameTF.setBounds(190, 80, 180, 26);

        amount.setText("Transaction AMT:");
        ourbank.add(amount);
        amount.setBounds(390, 50, 130, 20);

        amountTF.setEnabled(false);
        ourbank.add(amountTF);
        amountTF.setBounds(490, 50, 130, 26);

        currency.setText("Currency:");
        ourbank.add(currency);
        currency.setBounds(390, 90, 120, 20);

        currencyTF.setEnabled(false);
        ourbank.add(currencyTF);
        currencyTF.setBounds(490, 90, 130, 26);

        reason.setText("Reason:");
        ourbank.add(reason);
        reason.setBounds(390, 130, 120, 20);

        reasonTF.setEnabled(false);
        ourbank.add(reasonTF);
        reasonTF.setBounds(490, 130, 130, 26);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), "Teller Information"));
        jPanel1.setEnabled(false);

        jLabel1.setText("Dealing Teller :");

        jLabel2.setText("Review Teller:");

        dealingTellerTF.setEnabled(false);

        reviewTellerTF.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dealingTellerTF)
                    .addComponent(reviewTellerTF, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dealingTellerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reviewTellerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showDetailPanelLayout = new javax.swing.GroupLayout(showDetailPanel);
        showDetailPanel.setLayout(showDetailPanelLayout);
        showDetailPanelLayout.setHorizontalGroup(
            showDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showDetailPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(showDetailPanelLayout.createSequentialGroup()
                .addGroup(showDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, showDetailPanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, showDetailPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, showDetailPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(showDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ourbank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otherbank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        showDetailPanelLayout.setVerticalGroup(
            showDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(27, 27, 27)
                .addComponent(ourbank, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(otherbank, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(showDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowDetailIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowDetailIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowDetailIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowDetailIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowDetailIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTF;
    private javax.swing.JLabel currency;
    private javax.swing.JTextField currencyTF;
    private javax.swing.JTextField dataTF;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dealingTellerTF;
    private javax.swing.JLabel flowNum;
    private javax.swing.JTextField flowNumTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel otherbank;
    private javax.swing.JPanel ourbank;
    private javax.swing.JTextField payAcctNumTF;
    private javax.swing.JLabel payeeAcctName;
    private javax.swing.JTextField payeeAcctNameTF;
    private javax.swing.JLabel payeeAcctNum;
    private javax.swing.JTextField payeeAcctNumTF;
    private javax.swing.JLabel payeeBankName;
    private javax.swing.JTextField payeeBankNameTF;
    private javax.swing.JLabel payeeBankNo;
    private javax.swing.JTextField payeeBankNoTF;
    private javax.swing.JLabel payerAcctName;
    private javax.swing.JTextField payerAcctNameTF;
    private javax.swing.JLabel payerBankName;
    private javax.swing.JTextField payerBankNameTF;
    private javax.swing.JLabel payerBankNo;
    private javax.swing.JTextField payerBankNoTF;
    private javax.swing.JLabel payeracctNum;
    private javax.swing.JTextField prestatusTF;
    private javax.swing.JLabel reason;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JTextField reviewTellerTF;
    private javax.swing.JPanel showDetailPanel;
    private javax.swing.JTextField statusTF;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
